### ISSUE TITLE
百度tts相关问题

### ISSUE THREAD

**Issue by L1cardo** [zhujisheng/HAComponent#1]
HA中使用百度tts ， ha会自动安装baidu-aip==1.6.6 
我一直提示无法安装，所以当我手动 pip install baidu-aip==1.6.6 的时候， 他需要安装pillow，问题就出在pillow，pillow是无法安装的，couldn't build wheel for pillow 
怎么解决？

**Comment by zhujisheng** [comment]
我想这是你python环境的问题。pillow是一个很常用的库。
