### ISSUE TITLE
中文README说明有误，望修改以免更多人疑惑

### ISSUE THREAD

**Issue by rangerzhou** [zhujisheng/HAComponent#2]
将文件"gaode_travel_time.py"放置在以下目录: "~/.homeassistant/custom_components/sensor/"。

应该为：

将文件"sensor.py, __init__.py, manifest.json"放置在以下目录: "~/.homeassistant/custom_components/gaode_travel_time/"。

**Comment by zhujisheng** [comment]
已更改
