### ISSUE TITLE
ha-restart时报错

### ISSUE THREAD

**Issue by rangerzhou** [zhujisheng/HAComponent#3]
2019-07-05 16:51:18 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
2956 Traceback (most recent call last):
2957   File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
2958     result = self.fn(*self.args, **self.kwargs)
2959   **File "/home/pi/.homeassistant/custom_components/tunnel2local/__init__.py", line 136, in stop_frpc**
2960     hass.data[DATA_TUNNEL2LOCAL].terminate()
2961   File "/usr/local/lib/python3.7/asyncio/subprocess.py", line 131, in terminate
2962     self._transport.terminate()
2963   File "/usr/local/lib/python3.7/asyncio/base_subprocess.py", line 150, in terminate
2964     self._check_proc()
2965   File "/usr/local/lib/python3.7/asyncio/base_subprocess.py", line 143, in _check_proc
2966     raise ProcessLookupError()
2967 ProcessLookupError

HA 版本：0.95.4

**Comment by zhujisheng** [comment]
这是因为frpc进程已经在此之前停止了造成的。将tunnel2local更新到最新版本试试。
