### ISSUE TITLE
调用服务："sensor.gaode_travel_time_update"，没有反应，需要传递参数吗

### ISSUE THREAD

**Issue by aalavender** [zhujisheng/HAComponent#4]
update确实执行了，我加了logger.info日志看到了，但是在“开发者工具”->“状态”里查看sensor的值没有任何变化，update_time都不变

**Comment by aalavender** [comment]
update确实执行了，我加了logger.info日志看到了，但是在“开发者工具”->“状态”里查看sensor的值没有任何变化，update_time都不变

**Comment by zhujisheng** [comment]
新版本可以调用服务`homeassistant.update_entity`试试
