### ISSUE TITLE
pulseaudio 蓝牙连接tts卡顿。 

### ISSUE THREAD

**Issue by hemingfei** [zhujisheng/HAComponent#5]
树莓派四刷HACHINA包。测试了蓝牙连接小度和小爱 都会卡顿。

**Comment by zhujisheng** [comment]
一般tts都是先下载了mp3，然后再播放的。所以估计卡顿一般是由于采样频率不支持造成的错觉。
集成中固定的采样频率是16000，有可能你的蓝牙音箱不支持。
因为手头没有对应的硬件，没法测试。
